spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/milan_store
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lamameelan32@gmail.com
    password: ivevewzysomlojaq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secretKey: X3kBtbafLa6bOvSY5VppbYI0DyEOk8EMXp3SgiU+PCI=

image:
  user: "images/users/"
  product: "images/products/"
  category: "images/categories/"
