spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/milan_store
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lamameelan32@gmail.com
    password: ivevewzysomlojaq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secretKey: X3kBtbafLa6bOvSY5VppbYI0DyEOk8EMXp3SgiU+PCI=

image:
  user: "images/users/"
  product: "images/products/"
  category: "images/categories/"

api:
  prefix: /store/v1

springdoc:
  swagger-ui:
    # Sort operations (endpoints) by HTTP method (GET, POST, etc.) in Swagger UI
    operations-sorter: method
    # Sort tags alphabetically in the Swagger UI for better organization
    tags-sorter: alpha
    # Custom path to access the Swagger UI (e.g., http://localhost:8080/milan-docs)
    path: /milan-docs
  api-docs:
    # Custom path to access the raw OpenAPI JSON (e.g., http://localhost:8080/milan-api-docs)
    path: /milan-api-docs

#  Access URLs for Swagger
#  Swagger UI: http://localhost:8080/milan-docs
#  OpenAPI JSON: http://localhost:8080/milan-api-docs